#42 gamer and game dev, can see the current price of EXO in USD and ETH straight from the wallet
Exodia-World/exodia.world-web-client pull request #7
Opened 2018-07-26 10:40 UTC by mohsen-norouzi

#42 gamer and game dev, can see the current price of EXO in USD and ETH straight from the wallet

2018-07-30 14:12 UTC, victorhuberta requested changes
I took the liberty to resolve conflicts and fix some issues caused by outdated master branch. A few things you should consider:

* Put both Ether and USD balance together with user's EXO balance instead of separating them into boxes. While you are at it, you should adjust the icon and font sizes as well.
* Make it clear that you are showing three different units of the same balance. Inside the staking info tab, it seems like "USD" and "Ethereum" are different kinds of values.
* CoinMarketCap API address should be stored in a file in `app/constants/`.
* Also, the unit should be called "Ether", not "Ethereum".

The suggestions aren't specific, but I hope they help. Good first commit though, thanks!

2018-08-01 04:59 UTC, victorhuberta reviewed
I think the two boxes are redundant. How about removing them? (I know, it hurts :( But unless we can find a use for it, it has no place in our codebase).

There is something awkward about the USD and ETH placements in the balance component. I'm not sure how to solve it though, so maybe @jacksonjunelee can suggest alternatives?

2018-08-01 09:43 UTC, victorhuberta approved these changes

2018-08-03 04:47 UTC, jacksonjunelee commented
i think it is fine. I think it really all depends on the wireframe. I personally like having a button or icon that changes the balance between ether and USD but i don't think that is anything major.

I think it is fine in the balance component because it is part of balance. However, another option to consider is to put the the USD/ether boxes to a different component.

2018-08-03 05:25 UTC, merged